name: Push Container to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v1

     - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

     - name: Build and Push to Heroku
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

          # - name: Build, Push and Deploy to Heroku
          #id: heroku
          #uses: jctaveras/heroku-deploy@v1.0.0
          #with:
          #email: ${{ secrets.HEROKU_EMAIL }}
          #api_key: ${{ secrets.HEROKU_API_KEY }}
          #app_name: ${{ secrets.HEROKU_APP_NAME }}
          #dockerfile: "FaceRecognition"
